# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    ui = None
    Form = None

    def __init__(self):
        self.Form = QtWidgets.QWidget()
        self.setupUi(self.Form)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(400, 241)
        Form.setMinimumSize(QtCore.QSize(400, 241))
        Form.setMaximumSize(QtCore.QSize(400, 241))
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnRun = QtWidgets.QPushButton(Form)
        self.btnRun.setGeometry(QtCore.QRect(20, 210, 71, 23))
        self.btnRun.setObjectName("btnRun")
        self.btnStop = QtWidgets.QPushButton(Form)
        self.btnStop.setEnabled(False)
        self.btnStop.setGeometry(QtCore.QRect(100, 210, 71, 23))
        self.btnStop.setObjectName("btnStop")
        self.btnExit = QtWidgets.QPushButton(Form)
        self.btnExit.setGeometry(QtCore.QRect(180, 210, 81, 23))
        self.btnExit.setObjectName("btnExit")
        self.spBoxSeconds = QtWidgets.QSpinBox(Form)
        self.spBoxSeconds.setGeometry(QtCore.QRect(270, 10, 111, 22))
        self.spBoxSeconds.setToolTipDuration(-1)
        self.spBoxSeconds.setMinimum(1)
        self.spBoxSeconds.setProperty("value", 4)
        self.spBoxSeconds.setObjectName("spBoxMilliseconds")
        self.lwDisplay = QtWidgets.QListWidget(Form)
        self.lwDisplay.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.lwDisplay.setObjectName("lwDisplay")
        self.keySequenceRecord = QtWidgets.QKeySequenceEdit(Form)
        self.keySequenceRecord.setGeometry(QtCore.QRect(270, 40, 61, 20))
        self.keySequenceRecord.setObjectName("keySequenceRecord")
        self.comBoxLanguage = QtWidgets.QComboBox(Form)
        self.comBoxLanguage.setGeometry(QtCore.QRect(270, 130, 111, 22))
        self.comBoxLanguage.setCurrentText("")
        self.comBoxLanguage.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.comBoxLanguage.setPlaceholderText("")
        self.comBoxLanguage.setDuplicatesEnabled(False)
        self.comBoxLanguage.setFrame(False)
        self.comBoxLanguage.setObjectName("comBoxLanguage")
        self.comBoxTranslation = QtWidgets.QComboBox(Form)
        self.comBoxTranslation.setEnabled(False)
        self.comBoxTranslation.setGeometry(QtCore.QRect(270, 180, 111, 22))
        self.comBoxTranslation.setObjectName("comBoxTranslation")
        self.chBoxTranslation = QtWidgets.QCheckBox(Form)
        self.chBoxTranslation.setGeometry(QtCore.QRect(270, 160, 81, 17))
        self.chBoxTranslation.setObjectName("chBoxTranslation")
        self.keySequenceOpenChat = QtWidgets.QKeySequenceEdit(Form)
        self.keySequenceOpenChat.setGeometry(QtCore.QRect(270, 70, 61, 20))
        self.keySequenceOpenChat.setObjectName("keySequenceOpenChat")
        self.lblRecord = QtWidgets.QLabel(Form)
        self.lblRecord.setGeometry(QtCore.QRect(340, 40, 49, 21))
        self.lblRecord.setObjectName("lblRecord")
        self.lblOpenChat = QtWidgets.QLabel(Form)
        self.lblOpenChat.setGeometry(QtCore.QRect(340, 70, 61, 21))
        self.lblOpenChat.setObjectName("lblOpenChat")
        self.keySqeuenceCloseChat = QtWidgets.QKeySequenceEdit(Form)
        self.keySqeuenceCloseChat.setGeometry(QtCore.QRect(270, 100, 61, 20))
        self.keySqeuenceCloseChat.setObjectName("keySqeuenceCloseChat")
        self.lblCloseChat = QtWidgets.QLabel(Form)
        self.lblCloseChat.setGeometry(QtCore.QRect(340, 100, 61, 21))
        self.lblCloseChat.setObjectName("lblCloseChat")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Game Voice to Text"))
        self.btnRun.setText(_translate("Form", "Run"))
        self.btnStop.setText(_translate("Form", "Stop"))
        self.btnExit.setText(_translate("Form", "Exit"))
        self.spBoxSeconds.setToolTip(_translate("Form", "Recording time in Seconds"))
        self.spBoxSeconds.setSuffix(_translate("Form", " Sec"))
        self.keySequenceRecord.setStatusTip(_translate("Form", "Key to start Listening"))
        self.keySequenceRecord.setKeySequence(_translate("Form", "G"))
        self.comBoxLanguage.setStatusTip(_translate("Form", "Language"))
        self.comBoxTranslation.setStatusTip(_translate("Form", "Translation Language"))
        self.chBoxTranslation.setText(_translate("Form", "Translate"))
        self.keySequenceOpenChat.setStatusTip(_translate("Form", "Key to open the Chat"))
        self.keySequenceOpenChat.setKeySequence(_translate("Form", "Enter"))
        self.lblRecord.setText(_translate("Form", "Record"))
        self.lblOpenChat.setText(_translate("Form", "Open Chat"))
        self.keySqeuenceCloseChat.setStatusTip(_translate("Form", "Key to open the Chat"))
        self.keySqeuenceCloseChat.setKeySequence(_translate("Form", "Enter"))
        self.lblCloseChat.setText(_translate("Form", "Close Chat"))
