# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    ui = None
    Form = None

    def __init__(self):
        self.Form = QtWidgets.QWidget()
        self.setupUi(self.Form)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 261)
        Form.setMinimumSize(QtCore.QSize(271, 261))
        Form.setMaximumSize(QtCore.QSize(271, 261))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 271, 261))
        self.tabWidget.setMaximumSize(QtCore.QSize(271, 261))
        self.tabWidget.setObjectName("tabWidget")
        self.tabRun = QtWidgets.QWidget()
        self.tabRun.setObjectName("tabRun")
        self.btnRun = QtWidgets.QPushButton(self.tabRun)
        self.btnRun.setGeometry(QtCore.QRect(10, 200, 71, 23))
        self.btnRun.setObjectName("btnRun")
        self.btnExit = QtWidgets.QPushButton(self.tabRun)
        self.btnExit.setGeometry(QtCore.QRect(170, 200, 81, 23))
        self.btnExit.setObjectName("btnExit")
        self.btnStop = QtWidgets.QPushButton(self.tabRun)
        self.btnStop.setEnabled(False)
        self.btnStop.setGeometry(QtCore.QRect(90, 200, 71, 23))
        self.btnStop.setObjectName("btnStop")
        self.lwDisplay = QtWidgets.QListWidget(self.tabRun)
        self.lwDisplay.setGeometry(QtCore.QRect(0, 0, 265, 192))
        self.lwDisplay.setObjectName("lwDisplay")
        self.tabWidget.addTab(self.tabRun, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.spBoxSleepTime = QtWidgets.QSpinBox(self.tabSettings)
        self.spBoxSleepTime.setGeometry(QtCore.QRect(130, 10, 111, 22))
        self.spBoxSleepTime.setToolTipDuration(-1)
        self.spBoxSleepTime.setMinimum(1)
        self.spBoxSleepTime.setMaximum(10000)
        self.spBoxSleepTime.setProperty("value", 100)
        self.spBoxSleepTime.setObjectName("spBoxSleepTime")
        self.spBoxRecording = QtWidgets.QSpinBox(self.tabSettings)
        self.spBoxRecording.setGeometry(QtCore.QRect(10, 10, 111, 22))
        self.spBoxRecording.setToolTipDuration(-1)
        self.spBoxRecording.setMinimum(1)
        self.spBoxRecording.setProperty("value", 4)
        self.spBoxRecording.setObjectName("spBoxRecording")
        self.keySequenceRecord = QtWidgets.QKeySequenceEdit(self.tabSettings)
        self.keySequenceRecord.setGeometry(QtCore.QRect(10, 40, 111, 20))
        self.keySequenceRecord.setStatusTip("")
        self.keySequenceRecord.setObjectName("keySequenceRecord")
        self.keySequenceOpenChat = QtWidgets.QKeySequenceEdit(self.tabSettings)
        self.keySequenceOpenChat.setGeometry(QtCore.QRect(10, 70, 111, 20))
        self.keySequenceOpenChat.setStatusTip("")
        self.keySequenceOpenChat.setObjectName("keySequenceOpenChat")
        self.keySqeuenceCloseChat = QtWidgets.QKeySequenceEdit(self.tabSettings)
        self.keySqeuenceCloseChat.setGeometry(QtCore.QRect(10, 100, 111, 20))
        self.keySqeuenceCloseChat.setStatusTip("")
        self.keySqeuenceCloseChat.setObjectName("keySqeuenceCloseChat")
        self.comBoxLanguage = QtWidgets.QComboBox(self.tabSettings)
        self.comBoxLanguage.setGeometry(QtCore.QRect(130, 40, 111, 22))
        self.comBoxLanguage.setStatusTip("")
        self.comBoxLanguage.setCurrentText("")
        self.comBoxLanguage.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.comBoxLanguage.setPlaceholderText("")
        self.comBoxLanguage.setDuplicatesEnabled(False)
        self.comBoxLanguage.setFrame(False)
        self.comBoxLanguage.setObjectName("comBoxLanguage")
        self.chBoxTranslation = QtWidgets.QCheckBox(self.tabSettings)
        self.chBoxTranslation.setGeometry(QtCore.QRect(130, 80, 81, 17))
        self.chBoxTranslation.setObjectName("chBoxTranslation")
        self.comBoxTranslation = QtWidgets.QComboBox(self.tabSettings)
        self.comBoxTranslation.setEnabled(False)
        self.comBoxTranslation.setGeometry(QtCore.QRect(130, 100, 111, 22))
        self.comBoxTranslation.setStatusTip("")
        self.comBoxTranslation.setObjectName("comBoxTranslation")
        self.btnSave = QtWidgets.QPushButton(self.tabSettings)
        self.btnSave.setGeometry(QtCore.QRect(0, 208, 41, 24))
        self.btnSave.setObjectName("btnSave")
        self.btnLoad = QtWidgets.QPushButton(self.tabSettings)
        self.btnLoad.setGeometry(QtCore.QRect(40, 208, 41, 24))
        self.btnLoad.setObjectName("btnLoad")
        self.tabWidget.addTab(self.tabSettings, "")
        self.tabCredits = QtWidgets.QWidget()
        self.tabCredits.setObjectName("tabCredits")
        self.txtBrowsCredits = QtWidgets.QTextBrowser(self.tabCredits)
        self.txtBrowsCredits.setGeometry(QtCore.QRect(0, 0, 265, 231))
        self.txtBrowsCredits.setObjectName("txtBrowsCredits")
        self.tabWidget.addTab(self.tabCredits, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Game Voice To Text"))
        self.btnRun.setText(_translate("Form", "Run"))
        self.btnExit.setText(_translate("Form", "Exit"))
        self.btnStop.setText(_translate("Form", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRun), _translate("Form", "Run"))
        self.spBoxSleepTime.setToolTip(_translate("Form", "Waiting time when opening and closing the Chat"))
        self.spBoxSleepTime.setSuffix(_translate("Form", " ms"))
        self.spBoxRecording.setToolTip(_translate("Form", "Recording time in Seconds"))
        self.spBoxRecording.setSuffix(_translate("Form", " sec"))
        self.keySequenceRecord.setToolTip(_translate("Form", "Key to start Recording"))
        self.keySequenceRecord.setKeySequence(_translate("Form", "G"))
        self.keySequenceOpenChat.setToolTip(_translate("Form", "Key to open the Chat"))
        self.keySequenceOpenChat.setKeySequence(_translate("Form", "Enter"))
        self.keySqeuenceCloseChat.setToolTip(_translate("Form", "Key to close the Chat"))
        self.keySqeuenceCloseChat.setKeySequence(_translate("Form", "Enter"))
        self.comBoxLanguage.setToolTip(_translate("Form", "Language in which the Programs listens"))
        self.chBoxTranslation.setText(_translate("Form", "Translate"))
        self.comBoxTranslation.setToolTip(_translate("Form", "Language in which the Program translates"))
        self.btnSave.setToolTip(_translate("Form", "Saves the Latest Settings"))
        self.btnSave.setText(_translate("Form", "Save"))
        self.btnLoad.setToolTip(_translate("Form", "Loads the latest Settings"))
        self.btnLoad.setText(_translate("Form", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("Form", "Settings"))
        self.txtBrowsCredits.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:700; text-decoration: underline;\">Credits</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">MilesJuddPorter -&gt; Creator of the Project</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Dearex -&gt; Contributor</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Glenomat -&gt; Contributor</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCredits), _translate("Form", "Credits"))
